spring.application.name=order-service

server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/orders_db

product.service.url=http://localhost:8081/api/products

payment.service.url=http://localhost:8083/api/payments